### ISSUE TITLE
Pin Doors Doesn't Work on Polus

### ISSUE THREAD

**Issue by RealMVC** [v0idp/AmongUsMenu#22]
If you pin a door on Polus, you can still open the door and walk through. The door will not close after opening it.

**Comment by v0idp** [comment]
This is due to the doors being locked down until you manually open them right ?

**Comment by RealMVC** [comment]
Yes

**Comment by v0idp** [comment]
maybe we can deactivate pin doors altogether for polus.

**Comment by std-nullptr** [comment]
We need to double check dPlainDoor_SetDoorway and make sure it's being called properly. If a door does open while it's supposed to be pinned it is supposed to close the door again right away. On Polus how this would look is that you run up to the door, unlock it, and by the time the menu goes away the door is closed again.

**Comment by v0idp** [comment]
fixed
