### ISSUE TITLE
Crash on Inject

### ISSUE THREAD

**Issue by 111KFIN** [v0idp/AmongUsMenu#27]
The Game gets Crash while injecting "AmongUsMenu.dll" on Among Us version 11.17s (Cracked)

**Comment by v0idp** [comment]
We do not support cracked version officially. you probably have the old 11.17s which wont work. you need the new one.

**Comment by 111KFIN** [comment]
target version for this Hack

**Comment by OsOmE1** [comment]
there are two versions of 2020.11.17
